iris-GmbH/iris-kas

README.md
Update README according to the changes in the image names with commit
https://github.com/iris-GmbH/meta-iris-base/commit/3be2018e12c0797a43e8f4f96e2d330715ff4435
=> [RDSBUG-568] Update README

buildspecs/build_firmware_images_develop.yml, include/kas-irma6-jenkins-populate-caches-release.yml, include/kas-irma6-jenkins-release.yml
- use multiconf specific include file for increased recipe parsing
- do not try to checkout identical named branches in meta layers for
develop or master branch runs
- fix sstate cache population on daily develop branch run
=> CI: Various bugfixes

buildspecs/build_firmware_images_develop.yml
Due to the "-k" flag, the --update flag does nothing here.
=> Buildspecs: Remove unnecessary --update flag

buildspecs/build_firmware_images_develop.yml
KAS for-all-repos does not understand the "-k" flag.
=> Buildspec: Fix feature CI builds

include/kas-irma6-qemuarm64.yml, include/kas-targets.yml
depends https://github.com/iris-GmbH/meta-iris-base/pull/28
=> Add qemuarm64 target

Jenkinsfile
Jenkins would fail if we try to access the CHANGE_BRANCH variable within
the sh script and it does not exist. We need to catch that case within
the Jenkins script itself.
=> Jenkinsfile: Fix variable assignment

kas-irma6-base.yml, patches/0001-Add-recipe-for-repo-2.16.7.patch, patches/0001-Fixup-for-the-repo-fetcher.patch
Current implementation of the repo fetcher is broken. These patches add
a working reimplementation of the repo fetcher.
Upstream-Status: In progress
=> [DEVOPS-265] Patches for repo support in yocto

Jenkinsfile, buildspecs/build_firmware_images_develop.yml, buildspecs/build_firmware_images_release.yml
These will be required for testing later on.
=> [DEVOPS-155] Add qemux86-64 image builds

.gitignore, README.md, container_read_sshdir.te, docker-compose.yml
Fixes https://github.com/iris-GmbH/iris-kas/issues/11
=> docker-compose: Enable support for SELinux

kas-irma6-base.yml
I think I forgot to set the new version for the next release on the last reintegration.
=> next version will be 2.0.2

kas-irma6-base.yml
Issues with GTest have been resolved.
=> [DEVOPS-390] Unfreeze poky layer

buildspecs/qemu_tests.yml, buildspecs/qemu_tests_pa.yml, kas-irma6-base.yml, patches/0001-Add-recipe-for-repo-2.19.patch, patches/0001-Implement-AUTOREV-for-local-manifest-repo-fetcher.patch
- Update Repo from 2.16 to 2.19
- Implement support for repo with localfile, supporting parallel builds with AUTOREV
DEVOPS-384
=> Implement repo localfile support

kas-irma6-base.yml
Include swupdate
Needed for: https://github.com/iris-GmbH/meta-iris-base/pull/45
=> Add meta-swupdate layer (refspec: dunfell)

Makefile, README.md
Also add make target for updating the toc
=> Add a toc to readme using doctoc

include/kas-irma6-imx8mp.yml
Add config to use irma6-r2 multiconfig
=> [RDPHOEN-1036] Add configuration for imx8mp-irma6r2 builds

.gitlab-ci.yml, .gitlab/common-template.yml, .gitlab/develop-template.yml, .gitlab/release-template.yml, CHANGELOG.md, Dockerfile, Makefile, README.md, include/ci/kas-ci-deploy-signing.yml, include/ci/kas-ci-release.yml, kas-irma6-base-common.yml, kas-irma6-base-deploy.yml, kas-irma6-base-maintenance.yml, kas-irma6-pa.yml, utils/set_layer_branchname.sh
- Signed swupdate artifacts
- Secure boot
- Add netboot image
=> ci: Add signing of builds

CHANGELOG.md, Makefile
Add makefile command for setting fixed refspecs on thirdparty meta layers
=> [RD-1240] Makefile: Set fixed thirdparty refspecs

.gitlab-ci.yml
- Skip container build by default
- Option to use freshly built container image within the same gitlab CI
run
=> Update gitlab CI

.gitlab/develop-template.yml
Automatically trigger a pipeline build if changes are pushed into
default branch (develop).
=> gitlab-ci: Auto build default branch on changes

.gitlab-ci.yml
See https://github.com/preslavmihaylov/todocheck/issues/196
=> gitlab-ci: Remove non-working todocheck for now

.gitlab-ci.yml
=> update systemtest base for fixing file permissions in runner workspace
