iris-GmbH/iris-kas

docker-compose.yml

Previously we assumed the build user is named "builder" within the KAS
container. However, this could be open to change. As the user is added
at runtime, we can mount the SSH folder to /etc/skel/.ssh instead, which
is the skeleton profile for newly created users. By doing so, we do not
rely on the naming of the build user

Don't assume build username within the docker container

---

kas-additional-targets.yml
kas-irma6-base.yml

Reducing the number of targets drastically reduces the time yocto spends
on parsing recipes. This commit moves seldom used targets from the main
kas config file into a separate config file.

Move seldom used targets into separate kas config

---

kas-irma6-base.yml

As the KAS repository is responsible for the overall versioning, the
DISTRO_VERSION should be defined there as well. Unfortunately, it is not
possible to set the variable outside of the distro config, however one
can refer to the value of an arbitrary variable from the local configs global
scope.

Move DISTRO_VERSION declaration to KAS repository

---

kas-irma6-base.yml

Since commit
https://github.com/ros/meta-ros/commit/ed0fce246bed1bb417307935d871ec1c2554354d
ros-common now also depends on ros-backports-hardknott-layer.

Add new ros-common dependency

---

kas-offline-build.yml

Use KAS' DL_DIR variable instead:
https://kas.readthedocs.io/en/latest/command-line.html#environment-variables

kas-offline-build.yml: Remove hardcoded variable

---

Dockerfile

QEMU 3.x networking does not work properly in docker, therefore upgraded QEMU to 5.2 from debian backports. 
xref: DEVOPS-153

Install QEMU from backports for bugfixes

---

Dockerfile

This command won't do anything, as apt is only called during the build
anyway.

Dockerfile: remove unnecessary apt hold statement

---

buildspecs/build_firmware_images_develop.yml

As the "-k" option is used within the latter KAS commands, the
configuration is not actually updated, if the cache population
conditions are met. Therefore this is now validated before the first,
config-relevant kas execution.

Codebuild: Fix cache population

---

Jenkinsfile
buildspecs/build_firmware_images_develop.yml

As the PR branch within jenkins does not contain the actual
branch name, this will not lead to the expected result when trying to
checkout the same branch in the layer repos.

Jenkins: Do not checkout PR branch on layer repos

---

Makefile
buildspecs/build_firmware_images_release.yml
conf/layer.conf
kas-irma6-base.yml

Previously, files for patching one of the yocto layer repositories had
to added within another yocto layer repository. This commit prepares the
KAS repository for adding patches directly within the KAS repository.
Existing tooling as been adapted for the inclusion of the "this"
repository.
As a side effect, the KAS repository is now also added to the yocto
BBLAYERS. This however does not seem to have a negative effect.

Enable adding patch files to KAS repository

---

kas-irma6-base.yml
patches/0001-Implement-AUTOREV-for-repo-fetcher.patch

A bug within our repo fetcher implementation, as well as in the bitbake
base class would cause empty hash results during recipe parsing.
Signed-off-by: Jasper Orschulko <Jasper.Orschulko@iris-sensing.com>

repo patches: Fix hash calculation

---

patches/0001-Add-recipe-for-repo-2.16.7.patch

Fix warnings during apply of repo patch, which could cause confusion as KAS
would falsely label them as errors.

Fix whitespace and trailing newline warnings

---

buildspecs/build_firmware_images_develop.yml

Fixes a bug, which would try to checkout an identical named branch when
running from a release branch.

jenkins: Do not try to checkout release branches

---

Dockerfile
Makefile

We need cmake when interacting directly with the source code (e.g.
building PA using google repo and crosstoolchain).

Dockerfile: Add cmake to image

---

Dockerfile

There has been a recent release of the KAS software, 2.6.1, which
contains the following necessary fixes for our CI setup:
https://github.com/siemens/kas/commit/15de0142d48cdc8e49507081650b3c25c851b00b
https://github.com/siemens/kas/commit/9732ec16f23fb2b8e9537f5d6f495b2ac8470225
We can therefore set our image to use this release, instead of the
latest development build.

Dockerfile: Fixed refspec 2.6.1 for kas base image

---

kas-irma6-base.yml

Commit [11d99fba1ff4da5b031e03c6504bc0e777615ac2](https://git.yoctoproject.org/poky/commit/?h=dunfell&id=11d99fba1ff4da5b031e03c6504bc0e777615ac2) in the poky layer
causes build errors when including gtest. Freeze poky refspec until this [issue
has been resolved](https://lists.openembedded.org/g/openembedded-core/topic/87483225#159473).

[DEVOPS-390] Freeze poky layer due to gtest bug

---

patches/0001-Implement-AUTOREV-for-repo-fetcher.patch

Due to a bug in repo, new branches aren't always discovered when running
`repo sync --fetch-submodules`. A workaround for this is to run
`repo sync` first, followed by the `repo sync --fetch-submodules`.

[DEVOPS-353] Repo fetcher: Fix submodule fetching

---

buildspecs/build_firmware_images_develop.yml
buildspecs/build_firmware_images_release.yml
buildspecs/license_compliance.yml
buildspecs/populate_download_mirror.yml

Due to a bug in AWS, it is currently not possible to mount multiple EFSs
into a codebuild instance. As a workaround we consolidate these into a
single EFS, until this has been resolved in upstream.
Upstream bug tracked at:
- https://github.com/aws/efs-utils/issues/114
- https://repost.aws/questions/QUXUoUoVAPQoGIYfuPpB-s7A/codebuild-adding-multiple-efs-suddenly-failes

[DEVOPS-389] codebuild: Use single EFS mount

---

Makefile

The `start-release` and `start-support` targets would use the HEAD of
the git branch after running kas for generating the fixed refspecs.
However, this would not account for temporary patch commits added by
KAS. Thus we manually checkout the original refspec as defined in the
kas config file, before running git describe.

Makefile: Handle patches during refspec generation

---

Dockerfile

Copy built binaries to /usr/bin instead of /usr/local/bin as the latter
is not part of the PATH variable within the KAS shell environment.

Dockerfile: Copy built binaries to /usr/bin

---

Makefile

The git flow support commands needs a base commit. This determines,
from which existing commit on the master branch shall be used as a basis
for the support release.

Makefile: Fix start-support target

---

include/kas-irma6-base-config.yml

Cloud jenkins does not use the docker-compose.yml. Adapt the HAB_DIR
path to point to the right location.

Fix: HAB_DIR point to the right dev_keys dir on cloud jenkins

---

.gitlab-ci.yml

Wipe should be able to run, even when all other jobs fail

gitlab-ci: Move wipe stage to start of pipeline

---

.gitlab-ci.yml
CHANGELOG.md

Workaround for https://jira.iris-sensing.net/browse/DEVOPS-553. We force
populate the caches on other branches than develop. This should
drastically decrease CI runtime on feature branches.

[DEVOPS-553] Workaround force populating caches

---

.gitlab-ci.yml
CHANGELOG.md

After internal discussions it was agreed that the risks of
having outdated branches writing to cache, thus risking the integrity of
the sstate cache outweight the possible benefits.

Revert force populating caches

---

include/ci/kas-ci-common.yml

Apparently there are issues when building pango using icecc.

Add pango to icecc blacklist

---

Makefile

Building and pushing the kas image is now done via gitlab CI.

Remove docker build and push from makefile

---

.gitlab-ci.yml

Add a job which can be run on schedule to check and delete faulty mirror
items.
This is after a faulty uninative-shim caused a massive increase
in feature branch builds.

gitlab: Add dl mirror maintenance job

---

.gitlab-ci.yml

Instead, a variable can be defined if needed.

gitlab-ci: Remove manual trigger for wipe sstate cache

---

kas-irma6-base-common.yml

Meta-ros is unmaintained since december 2021. Necessary packages are
migrated.

Remove meta-ros layers

---

.gitlab-ci.yml
.gitlab/common-template.yml
.gitlab/develop-template.yml
.gitlab/release-template.yml
.gitlab/test-qemu-template.yml

- Artifacts are now named, making it easier to differentiate downloaded
artifacts.
- Artifacts (except from the qemu build for technical reasons) are now
not additionally compressed in a tar.gz. Thus, individual files can
now be viewed and downloaded via gitlab, without having to download
all the artifacts at once.
- In case of build failure, the gitlab pipeline will now expose all
package relevant logs as artifacts. This should make debugging build
failures within the pipeline easier.

gitlab: Rework artifacts

---

kas-irma6-base-common.yml

Build of develop branch currently fails due to an update in cryptsetup which causes a patch in meta-imx to fail. An upstream issue entry has been created.
See:
- https://jira.iris-sensing.net/browse/RDPHOEN-1359
- https://source.denx.de/denx/meta-secure-imx/-/issues/3

meta-openembedded: temp freeze of upstream

---

.gitlab-ci.yml

Also, add an option to skip fitimage netboot build in pipeline run, which is done by default now.

gitlab-ci: Fix fitimage netboot artifact name
